### ISSUE TITLE
ElectronicCats

### ISSUE THREAD

**Issue by Alfa16bravo** [ElectronicCats/HunterCatNFC#10]
hello, I just received my huntercat nfc v2 rp2040, I updated them with the u2f file, I put them in bootloader it is detected in mass storage I put the file, the board restarts (no blue light), when I unplug it and I switch it on, nothing happens, no lights come on, the board only lights up and stays on only if I plug it in and unplug it. in the arduino serial monitor it initializes well my is in huntercat nfc v1.3.

**Comment by xpeqex** [comment]
Hi @Alfa16bravo 

Thank you for reaching out to us via GitHub.

We have received your email regarding the same issue you are experiencing, and we would like to continue addressing this matter through email. Please expect a response to your email soon.

If you have any additional information or further questions, please feel free to include them in the email thread. We are here to help and ensure that your concerns are addressed.

Thank you once again for reaching out to us, and we look forward to assisting you further.
