### ISSUE TITLE
Request to add a PayPal account to facilitate donation.

### ISSUE THREAD

**Issue by LuckyFishGeek** [ElectronicCats/HunterCatNFC#12]
Love these projects so much, I would like to buy you a coffee but I can't find your paypal account

**Comment by Marcelol52** [comment]
Hey there!

We love to hear you are enjoying our projects! ElectronicCats fosters open-source innovation by empowering projects that drive lasting change. Thanks for considering a donation and being part of our journey! You can donate through our PayPal QR attached here. 

Thanks in advance!

Kind Regards,

Marcelo 
Electronic Cats

![Codigo_QR_Donations_EC](https://github.com/ElectronicCats/HunterCatNFC/assets/139595394/cb9e3f75-7d52-47e8-b51d-36857c3e18dc)

**Comment by LuckyFishGeek** [comment]
I tried to scan the QR code to pay, but it failed. Can you provide me with your ID?

**Comment by sabas1080** [comment]
Now available in the README or in the link [Paypal ElectronicCats](https://paypal.me/electroniccats?country.x=MX&locale.x=es_XC), thank you for your donation
